package com.example.testtaskgithubapi.core.exception

object MyError {
    const val TIMEOUT_ERROR = "Connection time out"
    const val UNKNOWN_ERROR = "Unknown error"
}